apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "prometheus.name" . }}
spec:
  selector:
    app: {{ include "prometheus.name" . }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default "" }}
      {{- end }}
